package View;

import Controller.CadastroUsuariosController;
import Model.CadastroUsuarioModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaOpCadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaOpCadastroUsuarios
     */
    public TelaOpCadastroClientes() {
        initComponents();
        atualizarDadosTabela();
        setResizable(false);
        btnExcluir.setEnabled(false);
        btnAtualizarUsuario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAttId = new javax.swing.JButton();
        btnAtualizarUsuario = new javax.swing.JButton();
        btnAttTabela = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnInserirUsuario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaUsuarios = new javax.swing.JTable();
        lblTextoPesquisa = new javax.swing.JLabel();
        txtTextoPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/person.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(15, 214));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(656, 50));

        jPanel7.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel7.add(btnExcluir);

        btnAttId.setText("ATT COM ID");
        btnAttId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttIdActionPerformed(evt);
            }
        });
        jPanel7.add(btnAttId);

        btnAtualizarUsuario.setText("ATUALIZAR");
        btnAtualizarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarUsuarioActionPerformed(evt);
            }
        });
        jPanel7.add(btnAtualizarUsuario);

        btnAttTabela.setText("ATT TABELA");
        btnAttTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttTabelaActionPerformed(evt);
            }
        });
        jPanel7.add(btnAttTabela);

        btnSair.setText("SAIR");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel7.add(btnSair);

        btnInserirUsuario.setText("INSERIR NOVO");
        btnInserirUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnInserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirUsuarioActionPerformed(evt);
            }
        });
        jPanel7.add(btnInserirUsuario);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(15, 214));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Relação de Usuários")));

        tbListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nome Cliente", "Email Cliente", "CEP Clientes", "Endereço", "Fone"
            }
        ));
        tbListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaUsuariosMouseClicked(evt);
            }
        });
        tbListaUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListaUsuariosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbListaUsuariosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaUsuarios);

        lblTextoPesquisa.setText("Filtro pelo nome do cliente:");

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtTextoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTextoPesquisa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTextoPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTextoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed

        String nome = txtTextoPesquisa.getText();

        DefaultTableModel tableModel = (DefaultTableModel) tbListaUsuarios.getModel();

        tableModel.setNumRows(0);
        CadastroUsuariosController filtroController = new CadastroUsuariosController();
        ArrayList<CadastroUsuarioModel> listaUsuarios = filtroController.filtrarUsuarios(nome);
        // Missão: verificar na documentaçao técnica, o que é e o que faz o Iterator
        Iterator<CadastroUsuarioModel> iterator = listaUsuarios.iterator();

        while (iterator.hasNext()) {

            CadastroUsuarioModel usuario = iterator.next();
            tableModel.addRow(new Object[]{
                usuario.getId(),
                usuario.getUsername(),
                usuario.getEmail(),
                usuario.getLogin(),
                usuario.getPerfil()
            });

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnInserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirUsuarioActionPerformed
        /*TelaCadastroNovoUsuario novaTela = new TelaCadastroNovoUsuario();
        novaTela.setVisible(true);*/
    }//GEN-LAST:event_btnInserirUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
/*
        //Recuperou as informações da tabela
        Integer linhaSelecionada = tbListaUsuarios.getSelectedRow();
        String id_user = tbListaUsuarios.getValueAt(linhaSelecionada, 0).toString();
        String nomeUser = tbListaUsuarios.getValueAt(linhaSelecionada, 1).toString();
        String mensagem = "Deseja realmente excluir o usuario " + nomeUser + "?";
        int resposta = JOptionPane.showConfirmDialog(null, mensagem);

        if (resposta == 0) {
            CadastroUsuariosController op = new CadastroUsuariosController();
            op.deletarUsuariosController(id_user);
            String mensagem1 = "Registro excluido com sucesso!";
            JOptionPane.showMessageDialog(null, mensagem1);
            atualizarDadosTabela();
        } else if (resposta == 1) {
            String mensagem2 = "Exclusão negada!";
            JOptionPane.showMessageDialog(null, mensagem2);
        }*/
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    private void btnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarUsuarioActionPerformed
        //email, login, perfil
        //Recuperar os dados da lonha selecionada na tabela
        Integer linhaSelecionada = tbListaUsuarios.getSelectedRow();
        String id_user = tbListaUsuarios.getValueAt(linhaSelecionada, 0).toString();
        String nomeUser = tbListaUsuarios.getValueAt(linhaSelecionada, 1).toString();
        String email = tbListaUsuarios.getValueAt(linhaSelecionada, 2).toString();
        String login = tbListaUsuarios.getValueAt(linhaSelecionada, 3).toString();
        String perfil = tbListaUsuarios.getValueAt(linhaSelecionada, 4).toString();

        //Abre a janela da tela de Atualização de usuário
        TelaAtualizacaoUsuario tela = new TelaAtualizacaoUsuario();
        tela.setVisible(true);
        tela.atualizaCamposTela(id_user, nomeUser, email, login, perfil);
        tela.atualizaCamposTela(id_user, nomeUser, email, login, perfil);

    }//GEN-LAST:event_btnAtualizarUsuarioActionPerformed

    private void tbListaUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListaUsuariosKeyPressed
        if (tbListaUsuarios.getSelectedRow() != -1) {
            System.out.println("Tabela selecionada!");
            btnExcluir.setEnabled(true);
            btnAtualizarUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_tbListaUsuariosKeyPressed

    private void tbListaUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListaUsuariosKeyReleased
        if (tbListaUsuarios.getSelectedRow() != -1) {
            System.out.println("Tabela selecionada!");
            btnExcluir.setEnabled(true);
            btnAtualizarUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_tbListaUsuariosKeyReleased

    private void tbListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaUsuariosMouseClicked
        if (tbListaUsuarios.getSelectedRow() != -1) {
            System.out.println("Tabela selecionada!");
            btnExcluir.setEnabled(true);
            btnAtualizarUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_tbListaUsuariosMouseClicked

    private void btnAttIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttIdActionPerformed
        Integer linhaSelecionada = tbListaUsuarios.getSelectedRow();
        String id_user = tbListaUsuarios.getValueAt(linhaSelecionada, 0).toString();             
        
        String idUser = id_user;
        
        CadastroUsuariosController oper = new CadastroUsuariosController();
        oper.filtrarUsuarioAtualizarDadosBancoController(idUser);
        TelaAtualizacaoUsuario2 tela = new TelaAtualizacaoUsuario2();
        tela.setVisible(true);
       
   
    }//GEN-LAST:event_btnAttIdActionPerformed

    private void btnAttTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttTabelaActionPerformed
        
        atualizarDadosTabela();
    }//GEN-LAST:event_btnAttTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOpCadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttId;
    private javax.swing.JButton btnAttTabela;
    private javax.swing.JButton btnAtualizarUsuario;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirUsuario;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTextoPesquisa;
    private javax.swing.JTable tbListaUsuarios;
    private javax.swing.JTextField txtTextoPesquisa;
    // End of variables declaration//GEN-END:variables

    private void atualizarDadosTabela() {
        //Funçao que recebe uma arraylist cheia de dados
        //Decompor a arraylist
        //Pegar os dados decompostos 
        //Montar a tabela com os dados
        DefaultTableModel tableModel = (DefaultTableModel) tbListaUsuarios.getModel();

        tableModel.setNumRows(0);
        CadastroUsuariosController listaController = new CadastroUsuariosController();
        ArrayList<CadastroUsuarioModel> listaUsuarios = listaController.listarUsuarios();
        // Missão: verificar na documentaçao técnica, o que é e o que faz o Iterator
        Iterator<CadastroUsuarioModel> iterator = listaUsuarios.iterator();

        while (iterator.hasNext()) {

            CadastroUsuarioModel usuario = iterator.next();
            tableModel.addRow(new Object[]{
                usuario.getId(),
                usuario.getUsername(),
                usuario.getEmail(),
                usuario.getLogin(),
                usuario.getPerfil()
            });

        }
    }

    /*
    public void inicializarTabela() {
        tbListaUsuarios.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            ListSelectionModel botaoAtivado = (ListSelectionModel) e.getSource();

            // vai verificar se tem apenas uma linha selecionada.
            if (!botaoAtivado.isSelectionEmpty() && tbListaUsuarios.getSelectedRows().length == 1) {
                btnExcluir.setEnabled(true);
                btnAtualizarUsuario.setEnabled(true);
            } else {
                btnExcluir.setEnabled(false);
                btnAtualizarUsuario.setEnabled(false);
            }
        });
    }
     */
}
